sudo: required
services:
  - docker

before_install:
  - docker build -t fanzoudocker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run fanzoudocker/react-test npm test -- --coverage

after_success:
  - docker build -t fanzoudocker/multi-client ./client
  - docker build -t fanzoudocker/multi-nginx ./nginx
  - docker build -t fanzoudocker/multi-server ./server
  - docker build -t fanzoudocker/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push fanzoudocker/multi-client
  - docker push fanzoudocker/multi-nginx
  - docker push fanzoudocker/multi-server
  - docker push fanzoudocker/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: ComplexDockers
  env: ComplexDockers-env
  bucket_name: elasticbeanstalk-us-east-2-425848420508
  bucket_path: ComplexDockers
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
